### sign up
POST {{contextPath}}/user/sign-up
Content-Type: application/json

{
    "userNickname": "김멀캠",
    "userDevice" : "Device1234!!"
}

### find all user
GET {{contextPath}}/user

### find user by id
GET {{contextPath}}/user/id/{{manyDiaryUserId}}

### find user by nickname
GET {{contextPath}}/user/nickname/{{manyDiaryUserNickname}}

### delete user
PUT {{contextPath}}/user/delete/{{manyDiaryUserId}}