# 회원가입(로그인) -> 백업(비밀번호 수정) -> 로그아웃 -> 로그인(실패) -> 불러오기(비밀번호 초기화 + 로그인) -> 로그아웃 -> 로그인(성공)

### 1. sign-up
POST {{contextPath}}/user/sign-up
Content-Type: application/json

{
    "userNickname": "정현석",
    "userDevice": "정현석1234@@"
}


> {%
  client.global.set("access_token", response.body.data.accessToken);
  client.global.set("refresh_token", response.body.data.refreshToken);
%}

### 2. backup
PUT {{contextPath}}/user/backup
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "newPassword": "newPassword1234@@"
}

### 3. logout
POST {{contextPath}}/user/logout
Authorization: Bearer {{access_token}}

### 4. login (fail)
POST {{contextPath}}/user/login
Content-Type: application/json

{
    "userNickname": "김멀캠",
    "userDevice": "Device1234!!"
}

### 4. load
PUT {{contextPath}}/user/load
Content-Type: application/json

{
    "userNickname": "김멀캠",
    "userPassword": "newPassword1234@@",
    "userDevice": "newDevice1234!!"
}

> {%
  client.global.set("access_token", response.body.data.accessToken);
  client.global.set("refresh_token", response.body.data.refreshToken);
%}

### 5. logout
POST {{contextPath}}/user/logout
Authorization: Bearer {{access_token}}

### 6. login
POST {{contextPath}}/user/login
Content-Type: application/json

{
    "userNickname": "김멀캠",
    "userDevice": "newDevice1234!!"
}