### sign up
POST http://localhost:9090/api/v1/user/sign-up
Content-Type: application/json

{
    "userNickname": "김멀캠",
    "userDevice" : "Device1234!!"
}

### find all user
GET http://localhost:9090/api/v1/user

### find user by id
GET http://localhost:9090/api/v1/user/id/1

### find user by nickname
GET http://localhost:9090/api/v1/user/nickname/김싸피

### delete user
PUT http://localhost:9090/api/v1/user/delete/1